# tab_wiki.py — Contenu documentaire de l'aide intégrée Station Master
# Chaque fonction retourne une liste de tuples (tag, texte) pour le rendu tk.Text.
# Tags disponibles : h1, h2, h3, code, tip, warn, ok, "" (normal)


def wiki_quickstart():
    return [
        ("h1","  Station Master — Guide de démarrage rapide"),
        ("",  ""),
        ("h2","  Prérequis — Linux (Kubuntu/Ubuntu)"),
        ("code","  sudo apt install python3-tk python3-pil.imagetk"),
        ("code","  pip3 install ttkbootstrap tkintermapview requests pyserial matplotlib numpy --break-system-packages"),
        ("tip","  💡 Pillow (PIL) est nécessaire pour la Heatmap et le Grayline"),
        ("",  ""),
        ("h2","  Prérequis — Windows"),
        ("code","  pip install ttkbootstrap tkintermapview requests pyserial matplotlib numpy Pillow"),
        ("",  ""),
        ("h2","  Lancement"),
        ("code","  python3 station_master.py"),
        ("ok","  ✅ Peut être lancé depuis n'importe quel répertoire — les fichiers sont créés"),
        ("ok","     dans le dossier de station_master.py automatiquement"),
        ("",  ""),
        ("h2","  Premier lancement"),
        ("ok","  ✅ 1. Lancez station_master.py — config.ini créé automatiquement"),
        ("ok","  ✅ 2. Cliquez ⚙️ Paramètres → onglet 🏠 Station"),
        ("ok","  ✅ 3. Entrez votre indicatif (ex: ON5AM) et votre locator (ex: JO20SP)"),
        ("ok","  ✅ 4. Configurez votre port CAT si vous utilisez un transceiver"),
        ("ok","  ✅ 5. Enregistrez et redémarrez"),
        ("",  ""),
        ("h2","  Base de données DXCC — cty.dat"),
        ("",  "  Au premier démarrage, Station Master télécharge automatiquement cty.dat"),
        ("",  "  depuis country-files.com — la base de référence mondiale (340 entités DXCC)."),
        ("ok","  ✅ 4 482 préfixes reconnus — Ukraine, Malta, Géorgie, toutes les séries DL/R/U..."),
        ("tip","  💡 Le fichier cty.dat est placé dans le dossier de station_master.py"),
        ("tip","  💡 Sans connexion internet, le fichier existant est utilisé"),
        ("",  ""),
        ("h2","  Carte monde Grayline & Heatmap"),
        ("",  "  Au premier accès à ces onglets, l'image NASA est téléchargée (~1 Mo)"),
        ("",  "  et sauvegardée dans world_map_grayline.jpg (dossier de station_master.py)."),
        ("ok","  ✅ Téléchargement unique — réutilisée ensuite hors-ligne"),
        ("",  ""),
        ("h2","  Saisir votre premier QSO"),
        ("",  "  • Tapez l'indicatif dans le champ en haut à gauche"),
        ("",  "  • L'indicateur en dessous vous dit immédiatement si c'est un doublon"),
        ("",  "  • Cliquez 🔍 pour chercher les infos sur QRZ.com (clé API requise)"),
        ("",  "  • Remplissez Mode, RST, Commentaire puis 💾 SAVE"),
        ("",  ""),
        ("h2","  Import d'un logbook existant"),
        ("",  "  Bouton 📂 Import en haut → sélectionnez votre fichier .adi ou .adif"),
        ("ok","  ✅ Confirmations QSL lues automatiquement : LOTW_QSL_RCVD, EQSL_QSL_RCVD, QSL_RCVD"),
        ("ok","  ✅ Protection anti-doublons : un QSO déjà présent est ignoré"),
        ("tip","  💡 Formats supportés : HRD, WSJT-X, Log4OM, DXKeeper, QRZ export..."),
        ("tip","  💡 Pour les confirmations les plus complètes, exportez depuis QRZ.com"),
        ("",  ""),
        ("h2","  Raccourcis clavier — Bandes (F1-F7)"),
        ("",  "  Accès direct aux fréquences de référence sans quitter le clavier :"),
        ("code","  F1 → 160m  (1.840 MHz SSB)"),
        ("code","  F2 →  80m  (3.730 MHz SSB)"),
        ("code","  F3 →  40m  (7.100 MHz SSB)"),
        ("code","  F4 →  20m  (14.225 MHz SSB)"),
        ("code","  F5 →  15m  (21.290 MHz SSB)"),
        ("code","  F6 →  10m  (28.490 MHz SSB)"),
        ("code","  F7 →   6m  (50.150 MHz SSB)"),
        ("ok","  ✅ Syntonise le transceiver via CAT ET met à jour la fréquence dans la saisie QSO"),
        ("tip","  💡 Ces touches fonctionnent quel que soit l'onglet actif"),
    ]


def wiki_journal():
    return [
        ("h1","  📖 Onglet Journal"),
        ("",""),
        ("h2","  Navigation"),
        ("","  • Double-clic sur un QSO → édition complète"),
        ("","  • Clic droit → menu contextuel (supprimer, marquer, exporter)"),
        ("","  • Ctrl+A → sélectionner tout"),
        ("","  • Clic sur un QSO → affichage automatique sur la carte + fiche QRZ"),
        ("",""),
        ("h2","  Filtres"),
        ("","  Utilisez la zone Recherche à droite pour filtrer par :"),
        ("","  • Indicatif (partiel ou complet)"),
        ("","  • Bande : liste déroulante Bande"),
        ("","  • Mode : liste déroulante Mode"),
        ("","  • Bouton X : réinitialiser tous les filtres"),
        ("",""),
        ("h2","  Colonnes du tableau"),
        ("","  ID | Pays | Date | Heure UTC | Callsign | Nom | QTH | Bande | Mode"),
        ("","  RS envoyé | RS reçu | Distance km | Azimut | Statuts QSL | Commentaire"),
        ("",""),
        ("h2","  Raccourcis clavier"),
        ("code","  Double-clic  = Éditer le QSO"),
        ("code","  Ctrl+A       = Tout sélectionner"),
        ("code","  Clic droit   = Menu contextuel"),
        ("",""),
        ("h2","  Alerte doublon"),
        ("","  Dès que vous tapez un indicatif :"),
        ("ok","  🟢 Vert   = Premier QSO avec cette station"),
        ("tip","  🟡 Orange = Déjà travaillé sur d'autres bandes — nouvelle bande possible !"),
        ("warn","  🔴 Rouge  = Doublon exact sur la bande actuelle"),
    ]


def wiki_cluster():
    return [
        ("h1","  📡 DX Cluster & Carte Live"),
        ("",""),
        ("h2","  DX Cluster"),
        ("","  Connexion automatique au serveur configuré dans ⚙️ → DX Cluster"),
        ("","  Serveur par défaut : on0dxk.dyndns.org:8000"),
        ("",""),
        ("h2","  Filtres cluster"),
        ("","  • Bande   : affiche uniquement les spots sur la bande sélectionnée"),
        ("","  • Pays    : filtre par nom de pays (ex: Japan)"),
        ("","  • Appel   : filtre par préfixe ou indicatif partiel"),
        ("","  • 🔔 Alerte sonore : bip si un spot correspond aux alertes configurées"),
        ("",""),
        ("h2","  Code couleur des spots"),
        ("ok","  🟦 Bleu foncé  = Nouveau DXCC (jamais travaillé dans votre log)"),
        ("warn","  🟥 Rouge       = Correspond à vos alertes bande/pays configurées"),
        ("","  ⬜ Normal      = Spot standard"),
        ("",""),
        ("h2","  Double-clic sur un spot"),
        ("","  → Accorde le transceiver via CAT sur la fréquence du spot"),
        ("",""),
        ("h2","  Configurer les alertes"),
        ("","  Bouton ⚙️ Config alertes → entrez les bandes et pays à surveiller"),
        ("code","  Exemple bandes  : 20m,15m,10m"),
        ("code","  Exemple pays    : Japan,USA,Australia,China"),
        ("",""),
        ("h2","  Carte Live"),
        ("","  • Cliquez sur un QSO dans le Journal → le DX apparaît sur la carte"),
        ("","  • Une ligne rouge relie votre station au DX (short path)"),
        ("","  • Fond : OpenStreetMap (connexion internet requise)"),
        ("","  • Votre station est marquée 🏠 au démarrage"),
    ]


def wiki_cluster_enrichi():
    return [
        ("h1","  📡 DX Cluster enrichi — Guide complet"),
        ("",""),
        ("h2","  Sources de spots"),
        ("","  Station Master reçoit les spots DX de deux sources simultanées :"),
        ("ok","  ✅ Cluster TCP — connexion Telnet vers on0dxk.dyndns.org (configurable dans ⚙️ Paramètres)"),
        ("ok","  ✅ DXHeat.com — API JSON, rafraîchissement toutes les 60s, spots internationaux"),
        ("tip","  💡 La colonne Source indique l'origine de chaque spot : Cluster ou DXHeat"),
        ("",""),
        ("h2","  Barre de propagation"),
        ("","  En haut de l'onglet, les indicateurs solaires sont mis à jour toutes les 30 min :"),
        ("ok","  🟢 SFI (Solar Flux Index) — plus c'est élevé, mieux les hautes fréquences se propagent"),
        ("ok","  🟢 SSN — nombre de taches solaires"),
        ("ok","  ✅ K-index — vert (≤2) / jaune (≤4) / rouge (>4) = perturbation géomagnétique"),
        ("ok","  ✅ A-index — vert (≤7) / jaune (≤20) / rouge (>20)"),
        ("ok","  ✅ X-Ray — classe du rayonnement X solaire (A/B/C/M/X)"),
        ("ok","  ✅ Aurora — latitude du terminateur auroral en degrés"),
        ("",""),
        ("h2","  Barres d'activité par bande"),
        ("","  Les mini-barres colorées au-dessus des filtres montrent le nombre de spots"),
        ("","  reçus par bande depuis le démarrage. Couleur = bande radio :"),
        ("","  160m🔴  80m🟠  40m🟡  30m🟢  20m🔵  17m🟣  15m🩷  12m  10m🔴  6m🟡"),
        ("",""),
        ("h2","  Filtres avancés"),
        ("","  5 filtres combinables en temps réel :"),
        ("code","  Bande : ALL / 160m / 80m / 40m / 30m / 20m / 17m / 15m / 12m / 10m / 6m"),
        ("code","  Source : ALL / Cluster / DXHeat"),
        ("code","  Continent : ALL / EU / AS / NA / SA / OC / AF"),
        ("code","  Mode : ALL / CW / SSB / FT8 / FT4 / RTTY / JS8 / PSK / DIGI"),
        ("code","  🔍 Texte libre : recherche dans indicatif, pays, spotter, commentaire"),
        ("",""),
        ("h2","  Colonnes du tableau"),
        ("","  UTC • Âge • Freq (kHz) • Bande • Mode • Cont • Pays • DX Call • Az SP° • km • Spotter • Source • Info"),
        ("tip","  💡 Az SP° = azimut Short Path depuis JO20SP — Az LP = Az SP + 180°"),
        ("tip","  💡 km = distance approximative calculée depuis votre locator"),
        ("",""),
        ("h2","  Tooltip au survol"),
        ("","  Passez la souris sur un spot pour voir :"),
        ("","  DX Call • Pays • Continent • Fréquence • Mode • Az SP + Az LP • Distance • Spotter • Source • Âge"),
        ("","  Double-clic → syntonise le transceiver sur la fréquence du spot"),
        ("",""),
        ("h2","  Couleurs des lignes"),
        ("","  🟦 Bleu/violet — Nouveau DXCC (jamais travaillé dans votre log)"),
        ("","  🟥 Rouge sombre — Alerte bande/pays (configuré dans ⚙️ Config alertes)"),
        ("","  🟡 Jaune — Watchlist (préfixes rares : ex. 3B9, FT5, VK9X)"),
        ("","  🟢 Vert — Spot récent < 5 min"),
        ("","  🟡 Jaune — Spot 5-15 min"),
        ("","  ⬛ Gris — Spot > 15 min"),
        ("",""),
        ("h2","  Watchlist — stations rares"),
        ("","  Configurez des préfixes à surveiller en priorité :"),
        ("ok","  1. Cliquez ⚙️ Config dans la barre de filtres"),
        ("ok","  2. Section 'Watchlist' : entrez les préfixes séparés par virgule"),
        ("code","  Exemple : 3B9,FT5,VK9X,ZL9,VP6,KH1,E5,BS7,3Y,VK0M"),
        ("ok","  3. Ces spots apparaissent en jaune avec alerte sonore"),
        ("",""),
        ("h2","  Export CSV"),
        ("","  Bouton 💾 CSV → exporte tous les spots en mémoire (jusqu'à 300) vers un fichier CSV"),
        ("","  Colonnes : UTC, Freq, Band, Mode, Cont, Pays, DX Call, Spotter, Source, Info"),
        ("",""),
        ("h2","  Menu clic droit sur un spot"),
        ("","  Clic droit sur n'importe quel spot dans le tableau → menu contextuel :"),
        ("ok","  ✅ 📋 Copier l'indicatif     → copie le callsign dans le presse-papier"),
        ("ok","  ✅ 🔍 Lookup QRZ.com         → ouvre la fiche QRZ du DX dans le navigateur"),
        ("ok","  ✅ 📻 Syntoniser radio        → accord immédiat du transceiver sur la fréquence"),
        ("ok","  ✅ ✏️ Pré-remplir saisie QSO → remplit indicatif + fréquence + mode dans l'onglet Journal"),
        ("tip","  💡 Double-clic sur un spot = syntonise directement (raccourci)"),
        ("tip","  💡 Le pré-remplissage bascule automatiquement sur l'onglet Journal"),
        ("",""),
        ("h2","  Stats session"),
        ("","  La barre d'activité affiche en temps réel :"),
        ("","  • Nombre total de spots reçus depuis le démarrage"),
        ("","  • Nombre de pays différents vus"),
        ("","  • Durée de la session (heure:minute)"),
    ]


def wiki_spot_history():
    return [
        ("h1","  📜 Onglet Spot History — Historique des spots DX"),
        ("",""),
        ("","  L'onglet Spot History conserve une trace de tous les spots DX reçus"),
        ("","  depuis le démarrage de la session (jusqu'à 1000 spots)."),
        ("",""),
        ("h2","  Contenu du tableau"),
        ("","  Chaque ligne correspond à un spot reçu :"),
        ("code","  UTC • Fréquence (kHz) • Bande • Mode • Pays • DX Call • Spotter • Source • Info"),
        ("tip","  💡 La colonne Source indique l'origine : Cluster (TCP) ou DXHeat (API)"),
        ("",""),
        ("h2","  Filtres"),
        ("","  Trois filtres combinables en temps réel :"),
        ("ok","  ✅ Bande   : ALL / 160m / 80m / 40m / ... / 6m"),
        ("ok","  ✅ Mode    : ALL / CW / SSB / FT8 / FT4 / RTTY / DIGI"),
        ("ok","  ✅ 🔍 Texte libre : recherche dans indicatif, pays, spotter, info"),
        ("tip","  💡 Les filtres s'appliquent instantanément sans rechargement"),
        ("",""),
        ("h2","  Interactions"),
        ("ok","  ✅ Double-clic sur un spot → syntonise le transceiver sur la fréquence"),
        ("ok","  ✅ Clic droit → menu contextuel : copier indicatif, lookup QRZ, syntoniser"),
        ("ok","  ✅ Bouton 🗑️ Effacer → vide l'historique de la session"),
        ("",""),
        ("h2","  Différence avec le DX Live"),
        ("","  Le DX Live affiche uniquement les spots récents (filtrés, triés, actualisés)."),
        ("","  Le Spot History conserve TOUS les spots reçus depuis le démarrage,"),
        ("","  y compris les spots anciens ou filtrés hors du DX Live."),
        ("tip","  💡 Utile pour retrouver un spot manqué ou analyser l'activité d'une session"),
    ]


def wiki_flex():
    return [
        ("h1","  📻 Onglet Flex-6500 — Guide complet"),
        ("",""),
        ("h2","  Connexion"),
        ("","  L'onglet Flex-6500 utilise deux connexions simultanées :"),
        ("code","  • Port 4992 (FlexAPI TCP) — fréquence, mode, filtre, interlock, infos radio"),
        ("code","  • Port 5003 (CAT SmartSDR) — puissance TX et S-meter en temps réel"),
        ("ok","  ✅ IP par défaut : 192.168.1.5 — modifiable dans la barre de connexion"),
        ("ok","  ✅ SmartSDR doit être lancé sur le même PC (127.0.0.1:5003)"),
        ("",""),
        ("h2","  Barre de propagation"),
        ("","  Identique à l'onglet DX Cluster — SFI, SSN, K-index, A-index, X-Ray, Aurora"),
        ("tip","  💡 K-index coloré : vert ≤2 / jaune ≤4 / rouge >4"),
        ("",""),
        ("h2","  VFO — Fréquence Active"),
        ("","  • Fréquence en grand format (52pt) — blanc en RX, rouge en TX"),
        ("","  • Bandeau coloré : couleur de la bande active"),
        ("","    160m🔴  80m🟠  40m🟡  30m🟢  20m🔵  17m🟣  15m🩷  10m🔴  6m🟡"),
        ("","  • Badge bande à droite (ex : 80m sur fond orange)"),
        ("","  • MODE — DIGU / CW / SSB / LSB / USB / AM / FM"),
        ("","  • Filtre BF — plage en Hz et largeur"),
        ("",""),
        ("h2","  TX / RX"),
        ("","  • Dot vert = RX / READY"),
        ("","  • Dot rouge = TX / TRANSMITTING (animé en temps réel)"),
        ("","  • État interlock SmartSDR affiché"),
        ("",""),
        ("h2","  Mesures"),
        ("","  S-Meter (ligne compacte) :"),
        ("","  • Valeur S1→S9+40dB colorée + dBm + mini-barre"),
        ("","  • Vert < S6 / Jaune S6-S9 / Rouge > S9"),
        ("",""),
        ("","  Puissance TX (VU-mètre vert→jaune→rouge) :"),
        ("","  • Valeur en Watts grand format, colorée selon niveau"),
        ("code","  Vert  0-55W  |  Jaune 55-82W  |  Rouge 82-100W"),
        ("","  • Barre VU-mètre 3 segments avec graduations 0/25/50/75/90/100W"),
        ("",""),
        ("","  SWR + ALC (ligne compacte) :"),
        ("","  • SWR vert (<1.5) / jaune (<2.0) / rouge (>2.0)"),
        ("","  • ALC en dB"),
        ("",""),
        ("h2","  Infos Radio"),
        ("","  • Ant RX / Ant TX — antenne active"),
        ("","  • Slices — nombre de slices actifs"),
        ("","  • Panadapts — nombre de panadapteurs"),
        ("","  • Filtre BF — valeurs lo/hi en Hz"),
        ("",""),
        ("h2","  Bandes & Modes rapides"),
        ("","  Un clic syntonise directement le Flex sur la fréquence FT8/DIGU de la bande :"),
        ("code","  160m→1.840  80m→3.573  40m→7.074  30m→10.136  20m→14.074"),
        ("code","  17m→18.100  15m→21.074  12m→24.915  10m→28.074  6m→50.313"),
        ("","  Modes rapides : CW / LSB / USB / AM / FM / DIGU / RTTY"),
        ("",""),
        ("h2","  Notes techniques"),
        ("warn","  ⚠️ Le streaming M| (fps=20) n'est pas supporté par certaines versions firmware"),
        ("warn","  ⚠️ La puissance est lue via le port CAT 5003 — SmartSDR doit être actif"),
        ("tip","  💡 Les tensions +13.8V et la température PA ne sont pas affichées"),
        ("tip","     (limitation FlexAPI : fps=0 pour ces mètres)"),
    ]


def wiki_awards():
    return [
        ("h1","  🏆 DXCC & Awards"),
        ("",""),
        ("h2","  Base de données DXCC — cty.dat"),
        ("","  Station Master utilise cty.dat (country-files.com) pour identifier les entités :"),
        ("ok","  ✅ 4 482 préfixes couverts — toutes séries DL/DA/DB/DC, RA/RK/UA/UB, UR/US/UT..."),
        ("ok","  ✅ 340 entités DXCC complètes"),
        ("ok","  ✅ 2 477 indicatifs spéciaux en correspondance exacte"),
        ("ok","  ✅ Appels portables gérés (W1AW/VE3 → Canada, DL1ABC/P → Allemagne)"),
        ("tip","  💡 cty.dat est téléchargé automatiquement au premier démarrage"),
        ("",""),
        ("h2","  Onglet DXCC"),
        ("","  • Bouton 🔄 Calculer depuis le log → analyse tous vos QSOs et groupe par entité"),
        ("","  • Filtre bande : voir le DXCC par bande spécifique"),
        ("","  • Filtre Afficher : Toutes / Confirmées / Non confirmées"),
        ("","  • Double-clic → ajouter des notes sur une entité"),
        ("ok","  ✅ Vert = entité confirmée (LoTW / eQSL / QSL physique / manuel)"),
        ("","  📡 Normal = travaillé mais pas encore confirmé"),
        ("",""),
        ("h2","  Sources de confirmation"),
        ("","  Une entité est marquée confirmée si au moins un QSO a :"),
        ("ok","  ✅ LOTW_QSL_RCVD = Y  (LoTW — via import ADIF HRD ou QRZ)"),
        ("ok","  ✅ EQSL_QSL_RCVD = Y  (eQSL)"),
        ("ok","  ✅ QSL_RCVD = Y        (QSL physique)"),
        ("ok","  ✅ Marquage manuel     (bouton ✅ Marquer comme CONFIRMÉ)"),
        ("",""),
        ("h2","  Marquer comme confirmé manuellement"),
        ("","  Sélectionnez une ou plusieurs entités → bouton ✅ Marquer comme CONFIRMÉ"),
        ("","  Pour retirer : bouton ❌ Retirer confirmation"),
        ("","  Les confirmations manuelles sont stockées dans la base SQLite"),
        ("",""),
        ("h2","  Onglet Awards → DXCC"),
        ("","  4 barres de progression : DXCC 100 / 200 / 300 / Honor Roll (340+)"),
        ("",""),
        ("h2","  WAZ — Worked All Zones"),
        ("","  40 zones CQ. Vert = travaillé, Rouge = manquant"),
        ("tip","  💡 Basé sur le mapping entité → zone CQ intégré au logiciel"),
        ("",""),
        ("h2","  WAS — Worked All States"),
        ("","  50 états USA. Basé sur le champ QTH des QSOs avec stations K/W/N"),
        ("","  La grille visuelle colorie les états travaillés en vert"),
        ("",""),
        ("h2","  IOTA"),
        ("","  Détection automatique des références dans les commentaires de QSOs"),
        ("code","  Exemple : commentaire contenant EU-005 ou OC-001"),
        ("tip","  💡 Pensez à noter la référence IOTA dans le champ Commentaire !"),
    ]


def wiki_graphs():
    return [
        ("h1","  📊 Graphiques & Statistiques"),
        ("",""),
        ("h2","  Onglet Statistiques"),
        ("","  Rapport texte complet avec :"),
        ("","  • QSOs par bande avec barre visuelle"),
        ("","  • QSOs par mode"),
        ("","  • QSOs par mois (12 derniers)"),
        ("","  • Top 15 pays DXCC estimés"),
        ("","  • Top 5 distances"),
        ("","  Bouton 📋 Copier → copie le rapport dans le presse-papier"),
        ("",""),
        ("h2","  Onglet Graphiques"),
        ("","  Choisissez le type dans la liste déroulante puis cliquez 📊 Générer :"),
        ("ok","  • QSOs par mois     — histogramme 24 derniers mois"),
        ("ok","  • QSOs par bande    — camembert coloré"),
        ("ok","  • QSOs par mode     — barres horizontales"),
        ("ok","  • Activité par heure — distribution UTC sur 24h"),
        ("ok","  • Progression DXCC  — courbe cumulative d'entités"),
        ("",""),
        ("h2","  Onglet Heatmap"),
        ("","  Carte mondiale de tous vos QSOs avec locator grid"),
        ("","  Trois modes d'affichage :"),
        ("","  • Entités DXCC   = couleur par pays"),
        ("","  • Densité QSOs   = gradient chaud selon le nombre de contacts"),
        ("","  • Continents     = couleur par continent avec légende"),
        ("tip","  💡 Requiert matplotlib + numpy (pip install matplotlib numpy)"),
    ]


def wiki_propagation():
    return [
        ("h1","  🌐 Propagation & Météo HF"),
        ("",""),
        ("h2","  Données solaires (hamqsl.com)"),
        ("","  Mise à jour automatique toutes les heures :"),
        ("ok","  SFI (Solar Flux Index)  — plus c'est élevé, meilleures sont les hautes bandes"),
        ("ok","  SN  (Sunspot Number)     — nombre de taches solaires"),
        ("ok","  K-index                  — activité géomagnétique (0-1 excellent, 5+ tempête)"),
        ("ok","  A-index                  — index géomagnétique journalier"),
        ("",""),
        ("h2","  Interprétation rapide"),
        ("ok","  🟢 SFI > 150 + K ≤ 2  = Conditions excellentes, 10m-15m ouverts"),
        ("tip","  🟡 SFI 100-150 + K ≤ 3 = Conditions normales"),
        ("warn","  🔴 K ≥ 5               = Tempête géomagnétique, évitez les hautes bandes"),
        ("",""),
        ("h2","  Greyline"),
        ("","  Calcul automatique pour votre locator :"),
        ("","  • Heure de lever et coucher solaire UTC"),
        ("","  • ± 30 minutes = fenêtre greyline"),
        ("","  • Bandes favorables greyline : 160m, 80m, 40m"),
        ("tip","  💡 La greyline est le moment idéal pour les DX longue distance !"),
        ("",""),
        ("h2","  Graphique MUF"),
        ("","  MUF estimée sur 24h selon SFI et K-index"),
        ("","  Les lignes pointillées indiquent les fréquences des bandes HF"),
        ("","  La ligne verticale blanche = heure actuelle UTC"),
        ("",""),
        ("h2","  🎯 VOACAP P2P — Propagation point à point"),
        ("","  Calcule la propagation prévisionnelle entre votre QTH et une entité DXCC cible."),
        ("ok","  ✅ Entrez l'indicatif ou le préfixe cible dans le champ '🎯 Destination'"),
        ("ok","  ✅ Cliquez 🎯 VOACAP P2P → ouvre voacap.com dans le navigateur"),
        ("","  Le lien est pré-rempli automatiquement avec :"),
        ("code","  • Coordonnées de ON5AM (locator JO20SP)"),
        ("code","  • Coordonnées du DX (lookup automatique dans cty.dat)"),
        ("code","  • Mois actuel"),
        ("code","  • SSN calculé depuis le SFI actuel (formule NOAA)"),
        ("tip","  💡 Si le préfixe n'est pas reconnu, les coordonnées par défaut sont utilisées"),
        ("tip","  💡 Le SSN est estimé depuis le SFI avec : SSN ≈ (SFI - 63) / 0.87"),
        ("",""),
        ("h2","  Liens utiles"),
        ("","  • 🌐 DX Maps    → spots temps réel par bande"),
        ("","  • 📡 VOACAP     → prévisions de propagation point à point"),
    ]


def wiki_qsl():
    return [
        ("h1","  🖨️ QSL, LoTW & Confirmations"),
        ("",""),
        ("h2","  Import ADIF avec confirmations"),
        ("","  Bouton 📂 Import → le fichier ADIF est analysé et les champs QSL lus :"),
        ("ok","  ✅ LOTW_QSL_RCVD = Y → LoTW confirmé"),
        ("ok","  ✅ EQSL_QSL_RCVD = Y → eQSL confirmé"),
        ("ok","  ✅ QSL_RCVD = Y       → QSL physique reçue"),
        ("ok","  ✅ Anti-doublons : un QSO déjà présent (même call/date/bande/mode) est ignoré"),
        ("tip","  💡 Source recommandée : export ADIF depuis QRZ.com (confirmations LoTW + eQSL à jour)"),
        ("tip","  💡 Source alternative : export HRD (Ham Radio Deluxe) — confirmations selon synchro LoTW"),
        ("",""),
        ("h2","  Export LoTW (ADIF)"),
        ("","  Menu clic droit dans le Journal → 📤 Exporter LoTW (ADIF)"),
        ("","  ou Clic droit → Exporter Sélection"),
        ("",""),
        ("","  Le fichier ADIF généré est compatible TQSL / LoTW :"),
        ("ok","  ✅ ADIF_VER 2.2.7"),
        ("ok","  ✅ STATION_CALLSIGN et MY_GRIDSQUARE inclus"),
        ("ok","  ✅ Sous-modes FT8/FT4/JS8/WSPR/JT65 automatiques"),
        ("",""),
        ("h2","  📡 Soumettre LoTW automatiquement"),
        ("","  Bouton 📡 Soumettre LoTW (auto) → soumet en un clic tous les QSOs non encore envoyés :"),
        ("ok","  ✅ Filtre automatiquement les QSOs avec Submitted = 0"),
        ("ok","  ✅ Génère un fichier ADIF temporaire dans votre dossier"),
        ("ok","  ✅ Lance TQSL automatiquement pour signature et upload"),
        ("ok","  ✅ Marque les QSOs concernés comme Submitted = 1 dans la base"),
        ("code","  Linux  : tqsl (doit être dans le PATH)"),
        ("code","  Windows: C:\\Program Files (x86)\\TrustedQSL\\tqsl.exe"),
        ("tip","  💡 Configurez le chemin TQSL dans ⚙️ → LoTW/TQSL si nécessaire"),
        ("warn","  ⚠️ TQSL doit être installé et votre certificat LoTW configuré au préalable"),
        ("",""),
        ("h2","  Workflow LoTW — étape par étape (ON5AM)"),
        ("ok","  ✅ Étape 1 : Onglet Journal → clic droit → 📤 Exporter LoTW (ADIF)"),
        ("ok","  ✅ Étape 2 : Signer avec TQSL :"),
        ("code","  tqsl -d -u -l \"ON5AM\" fichier_export.adi"),
        ("","         → génère un fichier .tq8 signé et l'uploade directement si connexion OK"),
        ("ok","  ✅ Étape 3 : Vérifier sur https://lotw.arrl.org → confirmations sous 24-48h"),
        ("tip","  💡 TQSL installé sur ce PC : /usr/bin/tqsl  (config.ini → [LOTW] tqsl_path)"),
        ("tip","  💡 Certificat : ON5AM — configuré dans TQSL via votre compte ARRL"),
        ("warn","  ⚠️ TQSL doit être ouvert au moins une fois pour configurer le certificat"),
        ("",""),
        ("h2","  Workflow LoTW (manuel alternatif)"),
        ("code","  1. Exporter → fichier .adi"),
        ("code","  2. Ouvrir dans TQSL → signer avec votre certificat"),
        ("code","  3. Uploader le .tq8 sur lotw.arrl.org"),
        ("tip","  💡 Configurez le chemin TQSL dans ⚙️ → LoTW/TQSL pour ouverture auto"),
        ("",""),
        ("h2","  QSL Reminder"),
        ("","  Onglet 📬 QSL Reminder → liste les QSOs anciens sans confirmation"),
        ("","  • Réglage du délai en jours (défaut 90j)"),
        ("","  • Filtre par système (LoTW / eQSL / QRZ / ClubLog)"),
        ("warn","  🔴 Rouge = plus d'un an sans confirmation"),
        ("tip","  🟡 Orange = au-delà du délai configuré"),
        ("",""),
        ("h2","  QSL Card"),
        ("","  Onglet 🖨️ QSL Card :"),
        ("","  1. Sélectionnez un QSO dans l'onglet Journal"),
        ("","  2. Cliquez 🖨️ Générer QSL Card"),
        ("","  3. Choisissez un thème (Classique / Nuit DX / Vintage / Contest)"),
        ("","  4. Modifiez le message et votre QTH si nécessaire"),
        ("","  5. 💾 Enregistrer PNG/PDF ou 🖨️ Imprimer directement"),
    ]


def wiki_cat():
    return [
        ("h1","  📻 Contrôle CAT & Mémoires fréquences"),
        ("",""),
        ("h2","  Protocole CAT"),
        ("","  Station Master utilise le protocole Kenwood CI-V (commandes FA/MD/SM/IF)"),
        ("","  Compatible avec la majorité des transceivers modernes :"),
        ("ok","  ✅ Kenwood : TS-590, TS-890, TS-2000, TS-480..."),
        ("ok","  ✅ Yaesu   : FT-991, FT-DX10, FT-DX101 (mode Kenwood émulé)"),
        ("ok","  ✅ Icom    : IC-7300, IC-7610 via adaptateur CI-V→RS232"),
        ("tip","  💡 Pour Icom, utilisez un câble USB-CI-V ou l'adaptateur RS-BA1"),
        ("",""),
        ("h2","  Configuration CAT"),
        ("","  ⚙️ Paramètres → 📻 CAT Transceiver :"),
        ("code","  Port  : COM4  (Windows) ou /dev/ttyUSB0 (Linux)"),
        ("code","  Baud  : 9600  (valeur la plus courante)"),
        ("","  Vitesses supportées : 4800, 9600, 19200, 38400, 57600"),
        ("",""),
        ("h2","  Données lues par CAT"),
        ("","  • VFO A : fréquence en temps réel → bande auto-détectée"),
        ("","  • Mode : LSB/USB/CW/FM/AM/DIG"),
        ("","  • S-Meter : barre de progression en temps réel"),
        ("","  • TX Status : indicateur 🔥 ON AIR lors de l'émission"),
        ("",""),
        ("h2","  Mémoires fréquences"),
        ("","  Onglet 📻 Mémoires :"),
        ("","  • 24 mémoires prédéfinies (FT8/SSB/CW toutes bandes)"),
        ("","  • Clic sur un bouton = accord immédiat du transceiver via CAT"),
        ("","  • Couleurs : 🟢 FT8/FT4  🔵 SSB  🟡 CW  🟣 DIG  🩵 FM"),
        ("","  • Ajout de mémoires personnalisées via le formulaire en haut"),
        ("","  • Stockées dans la base SQLite → persistantes entre sessions"),
    ]


def wiki_dashboard():
    return [
        ("h1","  🏠 Tableau de bord (Dashboard)"),
        ("",""),
        ("h2","  Vue d'ensemble"),
        ("","  Le Dashboard est le premier onglet — il centralise les informations les plus utiles :"),
        ("ok","  ✅ QSOs total + aujourd'hui"),
        ("ok","  ✅ Entités DXCC travaillées (via cty.dat) et confirmées"),
        ("ok","  ✅ Bande et fréquence active (via CAT)"),
        ("ok","  ✅ Résumé propagation solaire"),
        ("ok","  ✅ Greyline (lever/coucher solaire UTC)"),
        ("ok","  ✅ Dernier QSO enregistré"),
        ("ok","  ✅ Barres de progression Awards (DXCC 100/200/300, WAZ, WAS)"),
        ("ok","  ✅ Activité des 7 derniers jours"),
        ("ok","  ✅ Top 5 pays"),
        ("ok","  ✅ ⚡ Cadence QSOs : nombre de QSOs de la dernière heure + ratio journalier"),
        ("",""),
        ("h2","  Compteur DXCC confirmés"),
        ("","  Le compteur 'confirmés' combine trois sources :"),
        ("ok","  ✅ LOTW_QSL_RCVD = Y dans vos QSOs (LoTW)"),
        ("ok","  ✅ EQSL_QSL_RCVD = Y dans vos QSOs (eQSL)"),
        ("ok","  ✅ QSL_RCVD = Y dans vos QSOs (QSL physique)"),
        ("ok","  ✅ Confirmations manuelles via l'onglet DXCC"),
        ("tip","  💡 Les entités non reconnues par cty.dat sont exclues du compteur"),
        ("",""),
        ("h2","  Rapport PDF"),
        ("","  Bouton 📄 Générer Rapport PDF → crée un rapport complet A4 avec :"),
        ("","  • Statistiques générales, QSOs par bande et mode"),
        ("","  • Top 20 pays, activité mensuelle sur 12 mois"),
        ("","  • Mis en forme professionnel, prêt à partager"),
        ("tip","  💡 Requiert : pip install reportlab"),
        ("",""),
        ("h2","  ⚡ Cadence QSOs — compteur de rythme"),
        ("","  Deux indicateurs de cadence affichés en temps réel :"),
        ("ok","  ✅ QSOs/h (dernière heure) : nombre de QSOs loggés dans les 60 dernières minutes"),
        ("ok","  ✅ Cadence/j : ratio QSOs ce jour / heures écoulées depuis minuit UTC"),
        ("tip","  💡 Utile en contest ou activité DX pour suivre votre rythme"),
        ("tip","  💡 Les deux compteurs se mettent à jour toutes les 30 secondes"),
        ("",""),
        ("h2","  Actualisation"),
        ("","  Le dashboard se rafraîchit automatiquement toutes les 30 secondes."),
    ]


def wiki_psk():
    return [
        ("h1","  📻 PSK Reporter"),
        ("",""),
        ("h2","  Qu'est-ce que PSK Reporter ?"),
        ("","  PSK Reporter est un réseau mondial de récepteurs SDR et stations amateurs"),
        ("","  qui logguent automatiquement les signaux entendus et les publient en temps réel."),
        ("",""),
        ("h2","  Onglet PSK Reporter"),
        ("","  Affiche quelles stations ont entendu votre signal dans la dernière heure."),
        ("ok","  • UTC : heure de réception"),
        ("ok","  • Callsign TX : votre station (ou station envoyant)"),
        ("ok","  • Entendu par : indicatif du récepteur"),
        ("ok","  • Locator RX : locateur Maidenhead du récepteur"),
        ("ok","  • Freq MHz / Bande / Mode / SNR"),
        ("ok","  • Pays du récepteur"),
        ("",""),
        ("h2","  Double-clic sur un spot"),
        ("","  → Affiche automatiquement le locateur du récepteur sur la Carte Live"),
        ("",""),
        ("h2","  Rafraîchissement"),
        ("","  Automatique toutes les 5 minutes via l'API PSK Reporter."),
        ("tip","  💡 Très utile pour vérifier la propagation et savoir qui vous entend !"),
        ("",""),
        ("h2","  Greyline animée (Carte Live)"),
        ("","  Le terminateur solaire est tracé sur la carte et mis à jour chaque minute."),
        ("","  • Case à cocher 🌓 Greyline animée pour l'activer/désactiver"),
        ("","  • Les points oranges indiquent la limite jour/nuit"),
        ("tip","  💡 Combinez la greyline avec les spots DX Cluster pour chasser les DX !"),
    ]


def wiki_config():
    return [
        ("h1","  ⚙️ Configuration"),
        ("",""),
        ("h2","  Fichiers principaux"),
        ("code","  station_master.py        ← script principal"),
        ("code","  station_master.db        ← base de données SQLite (tous vos QSOs)"),
        ("code","  config.ini               ← configuration (créé automatiquement)"),
        ("code","  cty.dat                  ← base DXCC (téléchargé automatiquement)"),
        ("code","  world_map_grayline.jpg   ← carte NASA (téléchargée automatiquement)"),
        ("ok","  ✅ Tous les fichiers sont créés dans le dossier de station_master.py"),
        ("ok","  ✅ Lancement possible depuis n'importe quel répertoire"),
        ("",""),
        ("h2","  Section [USER]"),
        ("code","  Callsign = ON5AM"),
        ("code","  Grid     = JO20SP   ← Locator Maidenhead 6 caractères"),
        ("",""),
        ("h2","  Section [CAT]"),
        ("code","  Windows  →  Port = COM4"),
        ("code","  Linux    →  Port = /dev/ttyUSB0  (ou /dev/ttyACM0)"),
        ("code","  Baud = 9600          ← Vitesse de communication"),
        ("tip","  💡 Flex-6500 : CAT via réseau TCP port 5003 — pas de port série nécessaire"),
        ("",""),
        ("h2","  Section [API]"),
        ("code","  QRZ_User = ON5AM     ← Login QRZ.com"),
        ("code","  QRZ_Pass = ****      ← Mot de passe QRZ"),
        ("code","  QRZ_Key  = xxxxxx    ← Clé API (abonnement XML requis)"),
        ("tip","  💡 Sans clé API QRZ, les lookups automatiques sont désactivés"),
        ("",""),
        ("h2","  Section [CLUSTER]"),
        ("code","  Host = on0dxk.dyndns.org"),
        ("code","  Port = 8000"),
        ("code","  Call = ON5AM"),
        ("",""),
        ("h2","  Section [DXCC]"),
        ("code","  Alert_Bands    = 20m,15m,10m"),
        ("code","  Alert_Countries= Japan,USA,Australia"),
        ("",""),
        ("h2","  Sauvegarde"),
        ("","  Bouton 💾 Backup → crée station_master_DATE.db dans le dossier Backups/"),
        ("","  Backup automatique à chaque fermeture de Station Master"),
        ("","  Les 10 derniers backups sont conservés automatiquement"),
    ]


def wiki_grayline():
    return [
        ("h1","  🌙 Onglet Grayline — Carte Monde Temps Réel"),
        ("",""),
        ("","  Visualisation de la Terre en temps réel avec la ligne terminatrice jour/nuit,"),
        ("","  les spots DX cluster et le tracé grand cercle vers n'importe quelle entité."),
        ("",""),
        ("h2","  Carte de fond"),
        ("","  La carte NASA (image satellite réelle) est téléchargée automatiquement"),
        ("","  au premier lancement depuis eoimages.gsfc.nasa.gov (~1 Mo)."),
        ("","  Elle est sauvegardée localement : world_map_grayline.jpg"),
        ("tip","  💡 Si le téléchargement échoue, une grille de secours bleue est utilisée"),
        ("ok","  ✅ La carte est partagée entre l'onglet Grayline et l'onglet Heatmap"),
        ("",""),
        ("h2","  Éléments affichés"),
        ("","  • Ligne terminatrice jour/nuit (actualisée toutes les 60 secondes)"),
        ("","  • Overlay nuit semi-transparent sur la zone nocturne"),
        ("","  • Point sub-solaire  ⊙  (cercle jaune = position du Soleil)"),
        ("","  • Spots DX cluster colorés par bande (200 derniers spots)"),
        ("","  • Marqueur rouge ON5AM (votre QTH)"),
        ("","  • Grand cercle au clic sur un spot (distance en km)"),
        ("",""),
        ("h2","  Légende des bandes"),
        ("code","  160m ■ rouge    80m ■ orange   40m ■ vert clair"),
        ("code","  20m  ■ cyan     15m ■ violet   10m ■ rose"),
        ("code","  6m   ■ blanc    2m  ■ gris"),
        ("",""),
        ("h2","  Interactions"),
        ("","  • Clic sur la carte → sélectionne le spot DX le plus proche (≤12°)"),
        ("","  • Grand cercle tracé depuis ON5AM vers l'entité cliquée"),
        ("","  • Distance affichée en km au milieu du tracé"),
        ("","  • Bouton ✖ Effacer tracé → supprime le grand cercle"),
        ("","  • Bouton 🔄 Rafraîchir → redessine immédiatement"),
        ("",""),
        ("h2","  📻 Bouton Syntoniser radio"),
        ("","  Après avoir cliqué sur un spot DX sur la carte :"),
        ("ok","  ✅ Le bouton 📻 Syntoniser radio s'active (en vert)"),
        ("ok","  ✅ Cliquez dessus → syntonise le transceiver sur la fréquence du spot via CAT"),
        ("ok","  ✅ Efface le grand cercle automatiquement après syntonisation"),
        ("tip","  💡 Le bouton reste désactivé (grisé) tant qu'aucun spot n'est sélectionné"),
        ("tip","  💡 Nécessite une connexion CAT active — vérifiez l'indicateur en haut"),
        ("",""),
        ("h2","  Actualisation automatique"),
        ("","  La carte se redessine automatiquement toutes les 60 secondes"),
        ("","  pour suivre l'évolution de la ligne terminatrice en temps réel."),
        ("tip","  💡 La carte s'adapte à la taille de la fenêtre lors du redimensionnement"),
    ]


def wiki_heatmap():
    return [
        ("h1","  🗺️ Onglet Heatmap — Carte QSOs"),
        ("",""),
        ("","  Visualisation géographique de tous vos QSOs sur la vraie carte satellite NASA."),
        ("","  Chaque point représente un locator Maidenhead distinct."),
        ("",""),
        ("h2","  Modes d'affichage"),
        ("",""),
        ("h3","  Entités DXCC"),
        ("","  Chaque entité DXCC reçoit une couleur unique."),
        ("","  Permet de voir instantanément la diversité géographique de vos QSOs."),
        ("",""),
        ("h3","  Densité QSOs"),
        ("","  Couleur du point selon le nombre de QSOs dans ce locator :"),
        ("ok","  Jaune pâle = 1 QSO   →   Rouge vif = maximum"),
        ("","  La taille du point grandit aussi avec le nombre de QSOs."),
        ("",""),
        ("h3","  Continents"),
        ("","  Un point par locator, coloré par continent :"),
        ("code","  🔵 Europe  🔴 Asie  🟢 Am.Nord  🟠 Am.Sud  🟣 Afrique  🩵 Océanie"),
        ("","  Une légende apparaît en bas à gauche de la carte."),
        ("",""),
        ("h2","  Éléments fixes"),
        ("","  • Marqueur orange ★ ON5AM (votre position exacte)"),
        ("","  • Bandeau de statistiques en haut : QSOs · locators · entités"),
        ("",""),
        ("h2","  Carte de fond"),
        ("","  Même image satellite NASA que l'onglet Grayline (world_map_grayline.jpg)."),
        ("tip","  💡 Si la carte n'est pas encore téléchargée, une grille bleue est utilisée"),
        ("",""),
        ("h2","  Filtre par année"),
        ("","  Analysez votre activité sur une période spécifique :"),
        ("ok","  ✅ Liste déroulante Année : Toutes / 2020 / 2021 / ... / année courante"),
        ("ok","  ✅ Sélectionnez une année → seuls les QSOs de cette année sont affichés"),
        ("ok","  ✅ 'Toutes' = toute la base (comportement par défaut)"),
        ("tip","  💡 Utile pour comparer deux années d'activité ou isoler une période DX"),
        ("",""),
        ("h2","  Utilisation"),
        ("ok","  ✅ Sélectionnez le mode dans la liste déroulante"),
        ("ok","  ✅ Sélectionnez optionnellement une année dans le filtre Année"),
        ("ok","  ✅ Cliquez 🔄 Générer la heatmap pour redessiner"),
        ("ok","  ✅ La carte se redimensionne automatiquement avec la fenêtre"),
        ("warn","  ⚠️ Seuls les QSOs avec un locator Maidenhead renseigné sont affichés"),
        ("tip","  💡 Importez depuis QRZ.com ou WSJT-X pour avoir le maximum de locators"),
    ]


def wiki_ft8_decodium():
    return [
        ("h1","  📡 FT8 Live & Decodium"),
        ("",""),
        ("h2","  Qu'est-ce que Decodium ?"),
        ("","  Decodium est un décodeur FT8 indépendant qui s'exécute en parallèle"),
        ("","  de votre transceiver Flex-6500 / AetherSDR. Il envoie les décodes"),
        ("","  et les QSOs loggés via le protocole UDP WSJT-X (port 2237)."),
        ("tip","  💡 Decodium remplace WSJT-X pour le décodage FT8 — même protocole UDP"),
        ("",""),
        ("h2","  Indicateur de statut Decodium"),
        ("","  Dans l'onglet 📡 FT8 Live, un indicateur en haut à droite affiche :"),
        ("ok","  ✅ Decodium ✅ (3s)  120/min   → actif, dernière trame il y a 3s, 120 paquets/min"),
        ("warn","  ⚠️ Decodium ⚠ (30s)            → aucun paquet depuis 30 secondes"),
        ("","  ❌ Decodium ❌ inactif            → silence depuis plus de 60 secondes"),
        ("","  ❌ Decodium ❌                    → jamais reçu depuis le démarrage"),
        ("",""),
        ("h2","  Code couleur"),
        ("ok","  🟢 Vert   — paquet reçu il y a moins de 15 secondes (normal)"),
        ("warn","  🟡 Orange — aucun paquet depuis 15 à 60 secondes (Decodium peut être en pause)"),
        ("","  🔴 Rouge  — aucun paquet depuis plus de 60 secondes (Decodium arrêté ?)"),
        ("",""),
        ("h2","  Configuration UDP"),
        ("","  Dans config.ini, section [UDP] :"),
        ("code","  source = wsjtx          ← pour Decodium/WSJT-X"),
        ("code","  wsjtxport = 2237         ← port par défaut"),
        ("code","  multicastip = 224.0.0.1  ← groupe multicast"),
        ("tip","  💡 Si GridTracker est aussi actif : source = les_deux"),
        ("",""),
        ("h2","  Dépannage FT8 vide"),
        ("","  → Vérifiez que Decodium/WSJT-X est bien lancé et en mode FT8"),
        ("","  → Vérifiez le port UDP dans les paramètres de Decodium"),
        ("","  → Vérifiez source = wsjtx (pas gridtracker) dans config.ini"),
        ("code","  ls /dev/ttyUSB*    ← vérifier si l'interface USB/audio est détectée"),
        ("tip","  💡 L'indicateur Decodium ❌ en rouge est votre premier diagnostic"),
    ]


def wiki_spe_expert():
    return [
        ("h1","  ⚡ Ampli SPE Expert"),
        ("",""),
        ("h2","  Vue d'ensemble"),
        ("","  L'onglet ⚡ SPE permet de contrôler et monitorer l'amplificateur"),
        ("","  SPE Expert 1.3K-FA ou 2K-FA via port série USB, sans bloquer l'UI."),
        ("ok","  ✅ Thread série indépendant — Station Master reste fluide même si l'ampli est hors tension"),
        ("ok","  ✅ Reconnexion automatique si le port série est coupé / l'ampli redémarré"),
        ("",""),
        ("h2","  Connexion"),
        ("","  1. Branchez le câble USB entre le PC et la prise CAT/Serial du SPE Expert"),
        ("","  2. Identifiez le port :"),
        ("code","  ls /dev/ttyUSB*   ← généralement /dev/ttyUSB0"),
        ("","  3. Dans l'onglet ⚡ SPE, vérifiez Port et Baud (115200 par défaut)"),
        ("","  4. Cliquez 🔌 Connecter — ou attendez la reconnexion automatique (~5s)"),
        ("tip","  💡 Le port est sauvegardé dans config.ini section [SPE]"),
        ("",""),
        ("h2","  Panneau de statut"),
        ("","  Une fois connecté, les valeurs se mettent à jour toutes les 2 secondes :"),
        ("ok","  MODE        → Operate / Standby / Tune / Off"),
        ("ok","  TX / RX     → état d'émission (rouge si TX)"),
        ("ok","  BANDE       → bande courante détectée par l'ampli"),
        ("ok","  ANT TX/RX   → antenne sélectionnée"),
        ("ok","  PUISSANCE W → puissance de sortie (vert < 800W, orange < 1200W, rouge ≥ 1200W)"),
        ("ok","  SWR ATU     → SWR côté ATU intégré"),
        ("ok","  SWR ANT     → SWR côté antenne (orange > 1.5, rouge > 2.0)"),
        ("ok","  VPA / IPA   → tension et courant des tubes de puissance"),
        ("ok","  TEMP °C     → température (orange > 50°C, rouge > 65°C)"),
        ("warn","  ⚠️ Warning / Alarm → alertes de l'ampli en temps réel"),
        ("",""),
        ("h2","  Contrôles"),
        ("ok","  ⚡ OPERATE  → passe l'ampli en mode émission"),
        ("ok","  💤 STANDBY  → passe en veille (pas de HF)"),
        ("ok","  🔧 TUNE     → mode accord antenne"),
        ("",""),
        ("h2","  Changement de bande"),
        ("","  Le protocole SPE n'a pas de commande 'goto bande X' directe."),
        ("","  Station Master calcule le delta et envoie N × BAND_UP ou BAND_DOWN :"),
        ("code","  Bandes disponibles : 160m 80m 60m 40m 30m 20m 17m 15m 12m 10m 6m 4m"),
        ("","  1. Sélectionnez la bande cible dans le menu déroulant"),
        ("","  2. Cliquez → Go — les impulsions sont envoyées avec 150 ms d'intervalle"),
        ("tip","  💡 La bande actuelle est toujours visible dans le panneau STATUS"),
        ("",""),
        ("h2","  Sélection d'antenne"),
        ("","  Bouton Antenne Suivante → : cycle vers l'antenne TX suivante"),
        ("","  L'antenne active (ANT TX) est mise à jour au prochain polling (2s)"),
        ("",""),
        ("h2","  Droits d'accès (Linux)"),
        ("warn","  ⚠️ [Errno 13] Permission denied → votre utilisateur n'est pas dans le groupe dialout"),
        ("code","  sudo usermod -aG dialout $USER"),
        ("","  Déconnectez-vous puis reconnectez-vous pour que le changement soit pris en compte."),
        ("",""),
        ("h2","  Fermeture propre"),
        ("ok","  ✅ Fermer Station Master arrête proprement le thread série (plus de freeze)"),
        ("ok","  ✅ Le port USB est libéré immédiatement"),
    ]


def wiki_troubleshoot():
    return [
        ("h1","  🔧 Dépannage"),
        ("",""),
        ("h2","  Linux — Installation des dépendances"),
        ("code","  sudo apt install python3-tk python3-pil.imagetk"),
        ("code","  pip3 install ttkbootstrap tkintermapview requests pyserial matplotlib --break-system-packages"),
        ("warn","  ⚠️ Sans python3-pil.imagetk : la Heatmap et le Grayline ne fonctionnent pas"),
        ("",""),
        ("h2","  Linux — Port CAT série"),
        ("","  Sous Linux le port série n'est pas COM4 mais /dev/ttyUSB0 ou /dev/ttyACM0"),
        ("code","  ls /dev/tty* | grep -E 'USB|ACM'   ← trouver le bon port"),
        ("code","  sudo usermod -aG dialout $USER      ← droits d'accès (déconnexion requise)"),
        ("","  Configurez ensuite dans ⚙️ Paramètres → CAT"),
        ("",""),
        ("h2","  CAT ne fonctionne pas (Windows)"),
        ("warn","  RADIO OFF affiché → le port série n'est pas accessible"),
        ("","  • Vérifiez le port dans le Gestionnaire de périphériques"),
        ("","  • Vérifiez que le baud rate correspond au menu de votre transceiver"),
        ("","  • Fermez tout autre logiciel utilisant ce port (WSJT-X, FLDigi...)"),
        ("",""),
        ("h2","  Carte Grayline/Heatmap absente ou grille bleue"),
        ("","  → La carte NASA n'est pas encore téléchargée (premier lancement)"),
        ("","  → Vérifiez votre connexion internet et attendez quelques secondes"),
        ("","  → Si le téléchargement échoue, supprimer world_map_grayline.jpg et redémarrer"),
        ("tip","  💡 Fichier : world_map_grayline.jpg dans le dossier de station_master.py"),
        ("",""),
        ("h2","  Carte blanche (onglet Carte Live)"),
        ("","  → OpenStreetMap requiert une connexion internet"),
        ("","  → Vérifiez votre pare-feu / proxy d'entreprise"),
        ("",""),
        ("h2","  DX Cluster vide"),
        ("","  → Le serveur on0dxk.dyndns.org peut être temporairement hors ligne"),
        ("","  → Essayez un autre serveur : dxc.k3lr.com:7373 ou dx.sp5kab.pl:8000"),
        ("","  → Changez dans ⚙️ → DX Cluster"),
        ("",""),
        ("h2","  WSJT-X / FT8 non reçu"),
        ("","  → Vérifiez que WSJT-X envoie bien les UDP sur le port 2237"),
        ("","  → Menu WSJT-X : File → Settings → Reporting → UDP Server: 127.0.0.1:2237"),
        ("","  → L'indicateur RX DATA ✅ doit s'allumer en vert"),
        ("",""),
        ("h2","  DXCC confirmés affiche 0"),
        ("","  → Vos QSOs importés n'ont pas de champ QSL rempli"),
        ("","  → Solution : réimportez depuis QRZ.com (export ADIF complet)"),
        ("","    ou utilisez Ham Radio Deluxe après synchro LoTW"),
        ("tip","  💡 Les champs lus : LOTW_QSL_RCVD, EQSL_QSL_RCVD, QSL_RCVD"),
        ("",""),
        ("h2","  cty.dat manquant ou trop ancien"),
        ("","  → Supprimez le fichier cty.dat du dossier de station_master.py"),
        ("","  → Redémarrez : il sera retéléchargé automatiquement depuis country-files.com"),
        ("tip","  💡 Mise à jour recommandée : 1 à 2 fois par an"),
        ("",""),
        ("h2","  Graphiques absents"),
        ("code","  pip3 install matplotlib numpy"),
        ("",""),
        ("h2","  Erreur import ADIF"),
        ("","  → Vérifiez que le fichier est bien en format ADIF standard (.adi ou .adif)"),
        ("","  → Les fichiers Cabrillo (.cbr) ne sont pas supportés"),
        ("","  → Les doublons sont ignorés automatiquement (même call/date/bande/mode)"),
        ("",""),
        ("h2","  Performance lente avec beaucoup de QSOs"),
        ("","  → La base SQLite gère bien jusqu'à 100 000+ QSOs"),
        ("","  → Si lent : Backup → fermez → supprimez les vieux QSOs via clic droit"),
        ("",""),
        ("h2","  Alertes sonores silencieuses (Linux)"),
        ("","  Si vous n'entendez aucune alerte lors d'un nouveau spot DXCC :"),
        ("code","  paplay --version      ← vérifier si paplay (PulseAudio) est disponible"),
        ("code","  aplay --version       ← alternative ALSA"),
        ("code","  sudo apt install pulseaudio-utils   ← installer paplay si manquant"),
        ("ok","  ✅ Station Master essaie dans l'ordre : paplay → aplay → bip système"),
        ("tip","  💡 Sur Windows : winsound.Beep est utilisé (aucune dépendance)"),
        ("tip","  💡 Les alertes sonnent pour : nouveau DXCC, spot watchlist, alerte bande/pays"),
        ("",""),
        ("h2","  Version & informations"),
        ("ok","  Station Master V21.0 — développé pour ON5AM"),
        ("ok","  Plateforme : Linux (Kubuntu) et Windows"),
        ("ok","  Base de données : SQLite (station_master.db)"),
        ("ok","  DXCC lookup : cty.dat (country-files.com) — 4 482 préfixes"),
        ("ok","  Python 3.9+ requis"),
    ]
